Import the dataset 

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

Load the data set

In [2]:
data = pd.read_csv("ToyotaCorolla.csv",encoding="latin-1")

In [3]:
data.head()

Id                                           Model  Price  Age_08_04  \
0   1   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500         23   
1   2   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750         23   
2   3   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950         24   
3   4   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950         26   
4   5     TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750         30   

   Mfg_Month  Mfg_Year     KM Fuel_Type  HP  Met_Color  ... Central_Lock  \
0         10      2002  46986    Diesel  90          1  ...            1   
1         10      2002  72937    Diesel  90          1  ...            1   
2          9      2002  41711    Diesel  90          1  ...            0   
3          7      2002  48000    Diesel  90          0  ...            0   
4          3      2002  38500    Diesel  90          0  ...            1   

   Powered_Windows  Power_Steering  Radio  Mistlamps  Sport_Model  \
0                1               1      0          0            0   
1                0               1      0          0            0   
2                0               1      0          0            0   
3                0               1      0          0            0   
4                1               1      0          1            0   

   Backseat_Divider  Metallic_Rim  Radio_cassette  Tow_Bar  
0                 1             0               0        0  
1                 1             0               0        0  
2                 1             0               0        0  
3                 1             0               0        0  
4                 1             0               0        0  

[5 rows x 38 columns]

Drop the columns

In [4]:
data = data.drop(columns=["Id","Mfg_Month","Mfg_Year","Met_Color","Automatic","Gears","Quarterly_Tax","Weight","BOVAG_Guarantee","Guarantee_Period","Airbag_1","Airbag_2","Airco","Automatic_airco","Boardcomputer","CD_Player","Central_Lock","Powered_Windows","Power_Steering","Radio","Mistlamps","Sport_Model","Backseat_Divider","Metallic_Rim","Radio_cassette","Tow_Bar"],axis=1)

In [5]:
data.head()

Model  Price  Age_08_04     KM  \
0   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500         23  46986   
1   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750         23  72937   
2   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950         24  41711   
3   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950         26  48000   
4     TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750         30  38500   

  Fuel_Type  HP   Color    cc  Doors  Cylinders  Mfr_Guarantee  ABS  
0    Diesel  90    Blue  2000      3          4              0    1  
1    Diesel  90  Silver  2000      3          4              0    1  
2    Diesel  90    Blue  2000      3          4              1    1  
3    Diesel  90   Black  2000      3          4              1    1  
4    Diesel  90   Black  2000      3          4              1    1

Some information about the data set

In [6]:
data.shape

(1436, 12)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Model          1436 non-null   object
 1   Price          1436 non-null   int64 
 2   Age_08_04      1436 non-null   int64 
 3   KM             1436 non-null   int64 
 4   Fuel_Type      1436 non-null   object
 5   HP             1436 non-null   int64 
 6   Color          1436 non-null   object
 7   cc             1436 non-null   int64 
 8   Doors          1436 non-null   int64 
 9   Cylinders      1436 non-null   int64 
 10  Mfr_Guarantee  1436 non-null   int64 
 11  ABS            1436 non-null   int64 
dtypes: int64(9), object(3)
memory usage: 134.8+ KB


In [8]:
data.columns

Index(['Model', 'Price', 'Age_08_04', 'KM', 'Fuel_Type', 'HP', 'Color', 'cc',
       'Doors', 'Cylinders', 'Mfr_Guarantee', 'ABS'],
      dtype='object')

Some statistical information about the data set

In [9]:
data.describe()

Price    Age_08_04             KM           HP           cc  \
count   1436.000000  1436.000000    1436.000000  1436.000000   1436.00000   
mean   10730.824513    55.947075   68533.259749   101.502089   1576.85585   
std     3626.964585    18.599988   37506.448872    14.981080    424.38677   
min     4350.000000     1.000000       1.000000    69.000000   1300.00000   
25%     8450.000000    44.000000   43000.000000    90.000000   1400.00000   
50%     9900.000000    61.000000   63389.500000   110.000000   1600.00000   
75%    11950.000000    70.000000   87020.750000   110.000000   1600.00000   
max    32500.000000    80.000000  243000.000000   192.000000  16000.00000   

             Doors  Cylinders  Mfr_Guarantee         ABS  
count  1436.000000     1436.0    1436.000000  1436.00000  
mean      4.033426        4.0       0.409471     0.81337  
std       0.952677        0.0       0.491907     0.38975  
min       2.000000        4.0       0.000000     0.00000  
25%       3.000000        4.0       0.000000     1.00000  
50%       4.000000        4.0       0.000000     1.00000  
75%       5.000000        4.0       1.000000     1.00000  
max       5.000000        4.0       1.000000     1.00000

Check the null values in the dataset

No null values in the dataset 

In [10]:
data.isnull().sum()

Model            0
Price            0
Age_08_04        0
KM               0
Fuel_Type        0
HP               0
Color            0
cc               0
Doors            0
Cylinders        0
Mfr_Guarantee    0
ABS              0
dtype: int64

Handling the categorical columns

Level Encoding

In [11]:
encoder = LabelEncoder()

In [12]:
data["Model"] = encoder.fit_transform(data["Model"])
data["Color"] = encoder.fit_transform(data["Color"])
data["Fuel_Type"] = encoder.fit_transform(data["Fuel_Type"])

In [13]:
data.head()

Model  Price  Age_08_04     KM  Fuel_Type  HP  Color    cc  Doors  \
0    257  13500         23  46986          1  90      2  2000      3   
1    257  13750         23  72937          1  90      6  2000      3   
2    365  13950         24  41711          1  90      2  2000      3   
3    257  14950         26  48000          1  90      1  2000      3   
4    256  13750         30  38500          1  90      1  2000      3   

   Cylinders  Mfr_Guarantee  ABS  
0          4              0    1  
1          4              0    1  
2          4              1    1  
3          4              1    1  
4          4              1    1

Spliting the dataset into target and feature 

In [14]:
x = data.drop(columns="Price",axis=1)
y =data["Price"]

In [15]:
print(x.shape)

(1436, 11)


In [16]:
print(y.shape)

(1436,)


Spliting the data set into train test split

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [18]:
print(x.shape,x_train.shape,x_test.shape)

(1436, 11) (1148, 11) (288, 11)


In [19]:
x_train

Model  Age_08_04      KM  Fuel_Type   HP  Color    cc  Doors  Cylinders  \
899      15         62   59295          2   86      5  1300      5          4   
881      93         68   61568          2  110      6  1600      4          4   
310     115         40   38653          2  110      3  1600      5          4   
1145     87         75  101855          2  110      4  1600      5          4   
31       52         22   35199          2   97      2  1400      3          4   
...     ...        ...     ...        ...  ...    ...   ...    ...        ...   
1095     81         76  125778          2  110      4  1600      3          4   
1130     83         73  107108          2  110      4  1600      3          4   
1294    190         80   71740          2  110      6  1600      5          4   
860       6         63   64690          2   86      5  1300      3          4   
1126     93         80  110000          2  110      4  1600      4          4   

      Mfr_Guarantee  ABS  
899               1    1  
881               1    1  
310               1    1  
1145              0    0  
31                1    1  
...             ...  ...  
1095              0    1  
1130              0    0  
1294              0    0  
860               1    0  
1126              0    0  

[1148 rows x 11 columns]

Standerdization

In [20]:
scaler = StandardScaler()

In [21]:
x_train = scaler.fit_transform(x_train)

In [22]:
x_test = scaler.transform(x_test)

In [23]:
x_train

array([[-1.15070128,  0.32969109, -0.25437232, ...,  0.        ,
         1.20540095,  0.48963335],
       [-0.3610019 ,  0.64944782, -0.19405395, ...,  0.        ,
         1.20540095,  0.48963335],
       [-0.13826618, -0.84275022, -0.80214697, ...,  0.        ,
         1.20540095,  0.48963335],
       ...,
       [ 0.62106014,  1.28896126,  0.07587937, ...,  0.        ,
        -0.82959948, -2.04234453],
       [-1.24182043,  0.38298388, -0.11120576, ...,  0.        ,
         1.20540095, -2.04234453],
       [-0.3610019 ,  1.28896126,  1.09118108, ...,  0.        ,
        -0.82959948, -2.04234453]])

In [24]:
x_train.std()

0.9534625892455924

In [25]:
x_test

array([[-0.70522983, -0.30982235, -1.23079748, ...,  0.        ,
        -0.82959948,  0.48963335],
       [-0.50274281,  0.64944782,  0.30637886, ...,  0.        ,
         1.20540095,  0.48963335],
       [ 1.51200303,  0.16981273,  1.62191904, ...,  0.        ,
        -0.82959948, -2.04234453],
       ...,
       [-0.13826618, -0.84275022, -0.73086886, ...,  0.        ,
         1.20540095,  0.48963335],
       [ 0.34770267,  1.07579011, -1.82785114, ...,  0.        ,
        -0.82959948, -2.04234453],
       [-0.48249411,  0.16981273, -0.84723316, ...,  0.        ,
         1.20540095,  0.48963335]])

In [26]:
x_test.std()

0.8677169750764777

In [27]:
model = LinearRegression()
print("Load The Model")

Load The Model


In [28]:
model_train = model.fit(x_train,y_train)
print("Model Is trainned")

Model Is trainned


In [29]:
model_pred = model_train.predict(x_test)

In [30]:
model_pred

array([11633.31787045,  8800.63167311,  9408.42689554,  8670.80082651,
        9884.91639846,  7148.67065191,  9155.02186299,  8376.38821805,
       14639.79592115, 13610.25202006,  8785.08148693,  9075.57733087,
       13156.72158109, 14555.20643345, 10274.5007393 ,  8294.48514137,
       13119.11855487, 15738.49740965,  7958.84457757,  9381.83859957,
       13525.70933577, 17808.8537755 ,  7973.27557785, 10971.00776792,
        7530.06838117, 15834.64640187,  9466.1129066 ,  7281.32370381,
       15553.59897773, 15155.84873163,  8350.71263817, 10307.54993833,
        8711.34757931, 10303.07497901, 10087.61335646,  7574.32357202,
        9234.10023948,  9931.17855276, 15940.71529169,  9590.61111758,
        9638.40257723,  9483.97376229,  8039.89472478,  5505.70392015,
        6753.42810236, 17045.65209779,  9372.96784854, 10777.42902845,
        8883.10533536, 14056.60904715, 13354.20111661,  6274.89576462,
       14595.03635692, 15644.64473151,  5803.36784671,  7386.51654198,
      

In [31]:
y_test

594     10800
754      9950
630      7500
1259     9250
903      9750
        ...  
174     21950
1428     8450
297     12850
1435     6950
1009     8900
Name: Price, Length: 288, dtype: int64

In [32]:
acc_model = r2_score(y_test,model_pred)

In [33]:
print(acc_model)

0.8242389270798438
